- name: Add route
  command: route add default gw {{ gateway }}
  ignore_errors: yes

#- name: Add epel repo
#  yum: name={{ latest_epel_url }} state=present

#- name: Add remi repo
#  yum: name={{ latest_remi_url }} state=present

#- name: Add percona repo
#  yum: name={{ latest_percona_url }} state=present

- name: Install percona xtrabackup
  yum: name="percona-xtrabackup" state=latest update_cache=true

- name: Create script
  template: src=mysql_backup.j2 dest={{ script_path }}/{{ script_name }} backup=yes
  tags:
  - script

- name: Assign permission
  file: path={{ script_path }}/{{ script_name }} owner=root group=root mode=0744

- name: Create local backup dir
  file: path={{ backup_output }} owner=root group=root state=directory mode=0755

- name: Add crontab
  cron: name="backup {{ backup_name }}" minute="{{ cron_minute }}" hour="{{ cron_hour }}" job={{ script_path }}/{{ script_name }}
