#!/bin/bash

user=""
pass=""
host=127.0.0.1
port=38128
datadir=/data/lib/mongo
backup_name="YOUR BACKUP NAME"
out="/data/local-backup/mongo-${backup_name}"
useRep=true
isActive=true
oplog="--oplog"
dbpath="--dbpath ${datadir}"
connection_str="--host ${host} --port ${port}"
log=/var/log/mongodb/mongodump.log 
email_list="fake1@gmail.com,fake2@gmail.com"
mail_sender="YOUR MAIL SENDER"

which mongodump > /dev/null
if [ ! $? -eq 0 ]; then
    echo "You must install mongodump"
    exit -1
fi

rm -rfv ${out} &> ${log}

if [[ ! $useRep == "true" ]]; then
    oplog=""
fi

if [[ ! $isActive == "true" ]]; then
    connection_str=""
else
    dbpath=""
    if [[ ! -z $user ]] && [[ ! -z $pass ]]; then
        connection_str="${connection_str} --username ${user} --password ${pass}"
    fi
fi

mongodump -v  ${oplog} ${dbpath} ${connection_str} --out ${out} &>> ${log}
status=$?                                                                                                                                       
inter=$(route -n | grep "UG" | awk '{print $8}' | sort -n | uniq)
ip=$(ip a | grep inet | grep $inter | awk '{print $2}' | sed -e 's/\/.*$//')
[ ! $status -eq 0 ] && mail -r "${mail_sender}" -s "Backup Error at server with ip=${ip} and hostname=`hostname`" ${email_list} < ${log}

