#!/bin/bash

user=""
pass=""
host=127.0.0.1
port=38128
datadir=/data/lib/mongo
out=/data/local-backup/mongo-sopcast
useRep=true
isActive=true
oplog="--oplog"
dbpath="--dbpath ${datadir}"
connection_str="--host ${host} --port ${port}"
log=/var/log/mongodb/mongodump.log 

which mongodump > /dev/null
if [ ! $? -eq 0 ]; then
    echo "You must install mongodump"
    exit -1
fi

rm -rfv ${out} &> ${log}

if [[ ! $useRep == "true" ]]; then
    oplog=""
fi

if [[ ! $isActive == "true" ]]; then
    connection_str=""
else
    dbpath=""
    if [[ ! -z $user ]] && [[ ! -z $pass ]]; then
        connection_str="${connection_str} --username ${user} --password ${pass}"
    fi
fi

mongodump -v  ${oplog} ${dbpath} ${connection_str} --out ${out} &>> ${log}
