#!/bin/bash
root=${1:-root}
pass=${2:-"root pass"}
db_list=${3:-"db_list"}
host_list=${4:-"host_list"}
output=${5:-result}

function convert_user_to_host () {
   the_user=$1
   the_host_list=$2
   the_db=$3
   for the_host in $the_host_list; do
       echo "grant index, create temporary tables, create view, show view, create routine, alter routine, trigger, delete, insert, select, update, execute on \`${the_db}\`.* to '${the_user}'@'${the_host}';"  >> "${output}"
   done
}

echo "" > $output

for db in $db_list; do
echo "DB=$db"
some_users=$(mysql -u $root -p"$pass" -Ane "select distinct user as user_items from mysql.db where db='${db}'" | grep -v "user_items")
echo $some_users
   for user in $some_users; do
       echo "convert for $user..."
       convert_user_to_host "${user}" "${host_list}" "${db}"
   done
done
