#!/bin/bash
root=${1:-root}
root_pass=${2:-"root pass"}
db=${3:-db}
user=${4:-user}
user_pass=${5:-"user pass"}
host=${6:-host}
default_privileges="index, create temporary tables, create view, show view, create routine, alter routine, trigger, delete, insert, select, update, execute"

mysql -u $root -p"$root_pass" -Ane "create database if not exists $db;"
for host_item in $host; do
    mysql -u $root -p"$root_pass" -Ane "grant $default_privileges on \`$db\`.* to '$user'@'$host_item' identified by password '$user_pass';"
    mysql -u $root -p"$root_pass" -Ane "flush privileges;"
done
