#!/bin/bash

user_name=root
user_password="YOUR ROOT PASSWORD"
host="127.0.0.1"
parallel=4
backup_output="/data/local-backup"
log="/var/log/mysqld/backup.log"
galera_param="--galera-info"
myisam_param="--lock-wait-timeout=180 --lock-wait-threshold=20 --lock-wait-query-type=all --kill-long-queries-timeout=20 --kill-long-query-type=all"

function do_rm_backup() {
    rm -rvf ${backup_output}/* &> ${log}
}

function do_backup () {
    engine=$1
    use_galera=$2

    #echo "engine=$engine, use_galera=$use_galera"
    if [ $use_galera == "false" ]; then
        galera_pram=""
    fi
    if [ $engine == "innodb" ]; then
        myisam_param=""
    fi
    #echo "galera_param=$galera_param.myisam_param=$myisam_param."
    innobackupex  --user=${user_name} --password=${user_password} --host=${host} ${galera_param} --parallel=${parallel} ${myisam_param} ${backup_output} &>> ${log}
}
(
# Wait for lock on /var/lock/.myscript.lock (fd 200) for 10 seconds
flock -x -w 10 200 || exit 1
    do_rm_backup
    # DEPEND YOUR DB, CUSTOMIZE THIS COMMAND
    do_backup innodb true
) 200>/var/lock/.mysql_backup.lock

