- name: Setup haproxy user
  mysql_user: name={{ haproxy.user }} password="{{ haproxy.password }}" login_user={{ root_user }} login_password={{ root_password }} state=present host={{ item }}
  with_items:
  - "{{ mysql_host }}"
  ignore_errors: yes
  tags: 
  - create_haproxy_user
- name: debug sometimes
  debug:
    msg: "Print {{ root_user }} and {{ root_password }}"
  tags:
  - debug

