- name: Clean yum
  command: yum clean all

- name: Install default packages
  yum: name={{ item }} state=latest update_cache=true
  with_items:
  - xinetd
  - python-setuptools
  notify: start xinetd

- name: Install MySQL-python lib
  easy_install: name="MySQL-python"

