- hosts: all
  roles:
  - role: common

- hosts: dbservers
  roles:
  - role: mariadb-galera-cluster

- hosts: webservers
  roles:
  - role: nginx-web-server

- hosts: cacti
  roles:
  - role: cacti

- hosts: xtrabackup
  roles:
  - role: xtrabackup    
